### PR TITLE
Update npm deps

### PR DESCRIPTION
**Pull request by smorimoto**
New version of Biome performs more comprehensive checks

### CODE REVIEW

**Review by febuiles — DISMISSED** [review]
Thank you!

**Comment by smorimoto** [comment]
Anytime!

**Comment by febuiles** [comment]
@smorimoto I was under the impression that you'd be able to merge after my approval, apologies if that's not the case, I just merged. The change should go out with the next point release, if you think it makes sense to create a release from these changes please let me know.

**Review by febuiles — APPROVED** [review]

**Comment by smorimoto** [comment]
Unfortunately, I'm not a GitHub employee... 😢

**Comment by febuiles** [comment]
That can always be fixed, we're hiring: https://www.github.careers/careers-home/jobs :)

**Pull request merged**
